
#端口号
server:
  port: 8080

#数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/git-mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234

#mapper扫描相关
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
